---
- name: WARNING The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
  sysctl:
    name: net.core.somaxconn
    value: '1024'
    state: present
    reload: yes

- name: WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
  sysctl:
    name: vm.overcommit_memory
    value: '1'
    state: present
    reload: yes

- name: WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
  shell: echo 'never' >> /sys/kernel/mm/transparent_hugepage/enabled

- name: Add to '/etc/rc.d/rc.local'
  lineinfile:
    path: /etc/rc.d/rc.local
    line: echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
    mode: '0755'
