---
- hosts: vps
  become: yes
  vars:
    gitlab_ip: 10.10.0.52:8929
    gitlab_snipptes: 1
  tasks:
  - include_role:
      name: vps-user
    loop:
      - { exists: true, name: billy }
      - { exists: true, name: samchen }
      - { exists: true, name: nivek }