---
- name: Install 'python3' for ansible used
  yum:
    name: python3
    state: present
  register: rt

- name: Install 'pymongo' for ansible used
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pip:
    name: pymongo==3.12.2
    executable: pip3
  when: rt.changed
