---
- name: Check '{{ redis_exporter_path }}.linux-amd64.tar.gz' exists
  stat:
    path: "{{ redis_exporter_path }}.linux-amd64.tar.gz"
  register: rt_tar

- name: Copy 'redis_exporter-v{{ redis_exporter_version }}.linux-amd64.tar.gz'
  copy: 
    src: "redis_exporter-v{{ redis_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ redis_exporter_install_dir }}"
  when: not rt_tar.stat.exists

- name: Check '{{ redis_exporter_path }}' exists
  stat:
    path: "{{ redis_exporter_path }}"
  register: rt_path

- name: Extract '{{ redis_exporter_path }}.linux-amd64.tar.gz' tarball
  unarchive:
    src: "{{ redis_exporter_path }}.linux-amd64.tar.gz"
    dest: "{{ redis_exporter_install_dir }}"
    owner: root
    group: root
    remote_src: yes
  when: not rt_path.stat.exists

- name: Rename '{{ redis_exporter_path }}.linux-amd64' become '{{ redis_exporter_path }}'
  shell: "mv {{ redis_exporter_path }}.linux-amd64 {{ redis_exporter_path }}"
  when: not rt_path.stat.exists

- name: Setup systemd
  template:
    src: redis_exporter.systemd.j2
    dest: "{{ redis_exporter_systemd }}"
    owner: root
    group: root
    mode: '0644'
  notify: "Enable service on boot & Start redis_exporter service"